export default [{
  id: 1,
  title: 'LEMON CURD',
  category: 'Smoothie',
  caption: 'How to make the easiest homemade Lemon Curd with just four simple ingredients. It\'s sweet, tart, smooth and creamy, and can be used in so many ways from filling cakes, tarts, scones and so much more!',
  preparationTime: '2',
  isFavourite: true,
  cookTime: '3',
  servings: 5,
  description: 'Lemon curd is one of the easiest things to make, it’s a thick spread made from fresh lemons, sugar, eggs, and butter. It’s smooth, and creamy in texture with a bright, sweet, and zingy flavor perfect for using in desserts or simply spreading on toast for breakfast. Once you make this easy homemade version I guarantee you’ll never be tempted to pick up a jar at the store again because it doesn’t taste nearly as delicious! The secret to making the best lemon curd? Adding in cold butter at the end. It gives the curd the most delicious silky soft texture and thickens it beautifully.',
  ingredients: 'Lemon curd is one of the easiest things to make, it’s a thick spread made from fresh lemons, sugar, eggs, and butter. It’s smooth, and creamy in texture with a bright, sweet, and zingy flavor perfect for using in desserts or simply spreading on toast for breakfast. Once you make this easy homemade version I guarantee you’ll never be tempted to pick up a jar at the store again because it doesn’t taste nearly as delicious! The secret to making the best lemon curd? Adding in cold butter at the end. It gives the curd the most delicious silky soft texture and thickens it beautifully.',
  instructions: 'Lemon curd is one of the easiest things to make, it’s a thick spread made from fresh lemons, sugar, eggs, and butter. It’s smooth, and creamy in texture with a bright, sweet, and zingy flavor perfect for using in desserts or simply spreading on toast for breakfast. Once you make this easy homemade version I guarantee you’ll never be tempted to pick up a jar at the store again because it doesn’t taste nearly as delicious! The secret to making the best lemon curd? Adding in cold butter at the end. It gives the curd the most delicious silky soft texture and thickens it beautifully.',
  filePath: '../../../../assets/recipe/Cream-puffs-feature-1-360x495.jpg'
},
  {
    id: 2,
    title: 'LEMON CURD',
    category: 'Smoothie',
    caption: 'How to make the easiest homemade Lemon Curd with just four simple ingredients. It\'s sweet, tart, smooth and creamy, and can be used in so many ways from filling cakes, tarts, scones and so much more!',
    preparationTime: '2',
    isFavourite: false,
    cookTime: '3',
    servings: 5,
    description: 'Lemon curd is one of the easiest things to make, it’s a thick spread made from fresh lemons, sugar, eggs, and butter. It’s smooth, and creamy in texture with a bright, sweet, and zingy flavor perfect for using in desserts or simply spreading on toast for breakfast. Once you make this easy homemade version I guarantee you’ll never be tempted to pick up a jar at the store again because it doesn’t taste nearly as delicious! The secret to making the best lemon curd? Adding in cold butter at the end. It gives the curd the most delicious silky soft texture and thickens it beautifully.',
    ingredients: 'Lemon curd is one of the easiest things to make, it’s a thick spread made from fresh lemons, sugar, eggs, and butter. It’s smooth, and creamy in texture with a bright, sweet, and zingy flavor perfect for using in desserts or simply spreading on toast for breakfast. Once you make this easy homemade version I guarantee you’ll never be tempted to pick up a jar at the store again because it doesn’t taste nearly as delicious! The secret to making the best lemon curd? Adding in cold butter at the end. It gives the curd the most delicious silky soft texture and thickens it beautifully.',
    instructions: 'Lemon curd is one of the easiest things to make, it’s a thick spread made from fresh lemons, sugar, eggs, and butter. It’s smooth, and creamy in texture with a bright, sweet, and zingy flavor perfect for using in desserts or simply spreading on toast for breakfast. Once you make this easy homemade version I guarantee you’ll never be tempted to pick up a jar at the store again because it doesn’t taste nearly as delicious! The secret to making the best lemon curd? Adding in cold butter at the end. It gives the curd the most delicious silky soft texture and thickens it beautifully.',
    filePath: '../../../../assets/recipe/French-Toast-Feature-360x495.jpg',
  },
  {
    id: 3,
    title: 'LEMON CURD',
    category: 'Smoothie',
    caption: 'How to make the easiest homemade Lemon Curd with just four simple ingredients. It\'s sweet, tart, smooth and creamy, and can be used in so many ways from filling cakes, tarts, scones and so much more!',
    preparationTime: '2',
    isFavourite: false,
    cookTime: '3',
    servings: 5,
    description: 'Lemon curd is one of the easiest things to make, it’s a thick spread made from fresh lemons, sugar, eggs, and butter. It’s smooth, and creamy in texture with a bright, sweet, and zingy flavor perfect for using in desserts or simply spreading on toast for breakfast. Once you make this easy homemade version I guarantee you’ll never be tempted to pick up a jar at the store again because it doesn’t taste nearly as delicious! The secret to making the best lemon curd? Adding in cold butter at the end. It gives the curd the most delicious silky soft texture and thickens it beautifully.',
    ingredients: 'Lemon curd is one of the easiest things to make, it’s a thick spread made from fresh lemons, sugar, eggs, and butter. It’s smooth, and creamy in texture with a bright, sweet, and zingy flavor perfect for using in desserts or simply spreading on toast for breakfast. Once you make this easy homemade version I guarantee you’ll never be tempted to pick up a jar at the store again because it doesn’t taste nearly as delicious! The secret to making the best lemon curd? Adding in cold butter at the end. It gives the curd the most delicious silky soft texture and thickens it beautifully.',
    instructions: 'Lemon curd is one of the easiest things to make, it’s a thick spread made from fresh lemons, sugar, eggs, and butter. It’s smooth, and creamy in texture with a bright, sweet, and zingy flavor perfect for using in desserts or simply spreading on toast for breakfast. Once you make this easy homemade version I guarantee you’ll never be tempted to pick up a jar at the store again because it doesn’t taste nearly as delicious! The secret to making the best lemon curd? Adding in cold butter at the end. It gives the curd the most delicious silky soft texture and thickens it beautifully.',
    filePath: '../../../../assets/recipe/lemon-cookies-feature-360x495.jpg'
  },
  {
    id: 4,
    title: 'LEMON CURD',
    category: 'Smoothie',
    caption: 'How to make the easiest homemade Lemon Curd with just four simple ingredients. It\'s sweet, tart, smooth and creamy, and can be used in so many ways from filling cakes, tarts, scones and so much more!',
    preparationTime: '2',
    isFavourite: true,
    cookTime: '3',
    servings: 5,
    description: 'Lemon curd is one of the easiest things to make, it’s a thick spread made from fresh lemons, sugar, eggs, and butter. It’s smooth, and creamy in texture with a bright, sweet, and zingy flavor perfect for using in desserts or simply spreading on toast for breakfast. Once you make this easy homemade version I guarantee you’ll never be tempted to pick up a jar at the store again because it doesn’t taste nearly as delicious! The secret to making the best lemon curd? Adding in cold butter at the end. It gives the curd the most delicious silky soft texture and thickens it beautifully.',
    ingredients: 'Lemon curd is one of the easiest things to make, it’s a thick spread made from fresh lemons, sugar, eggs, and butter. It’s smooth, and creamy in texture with a bright, sweet, and zingy flavor perfect for using in desserts or simply spreading on toast for breakfast. Once you make this easy homemade version I guarantee you’ll never be tempted to pick up a jar at the store again because it doesn’t taste nearly as delicious! The secret to making the best lemon curd? Adding in cold butter at the end. It gives the curd the most delicious silky soft texture and thickens it beautifully.',
    instructions: 'Lemon curd is one of the easiest things to make, it’s a thick spread made from fresh lemons, sugar, eggs, and butter. It’s smooth, and creamy in texture with a bright, sweet, and zingy flavor perfect for using in desserts or simply spreading on toast for breakfast. Once you make this easy homemade version I guarantee you’ll never be tempted to pick up a jar at the store again because it doesn’t taste nearly as delicious! The secret to making the best lemon curd? Adding in cold butter at the end. It gives the curd the most delicious silky soft texture and thickens it beautifully.',
    filePath: '../../../../assets/recipe/No-bake-cheesecake-feature-360x495.jpg'
  },
  {
    id: 5,
    title: 'LEMON CURD',
    category: 'Smoothie',
    caption: 'How to make the easiest homemade Lemon Curd with just four simple ingredients. It\'s sweet, tart, smooth and creamy, and can be used in so many ways from filling cakes, tarts, scones and so much more!',
    preparationTime: '2',
    isFavourite: true,
    cookTime: '3',
    servings: 5,
    description: 'Lemon curd is one of the easiest things to make, it’s a thick spread made from fresh lemons, sugar, eggs, and butter. It’s smooth, and creamy in texture with a bright, sweet, and zingy flavor perfect for using in desserts or simply spreading on toast for breakfast. Once you make this easy homemade version I guarantee you’ll never be tempted to pick up a jar at the store again because it doesn’t taste nearly as delicious! The secret to making the best lemon curd? Adding in cold butter at the end. It gives the curd the most delicious silky soft texture and thickens it beautifully.',
    ingredients: 'Lemon curd is one of the easiest things to make, it’s a thick spread made from fresh lemons, sugar, eggs, and butter. It’s smooth, and creamy in texture with a bright, sweet, and zingy flavor perfect for using in desserts or simply spreading on toast for breakfast. Once you make this easy homemade version I guarantee you’ll never be tempted to pick up a jar at the store again because it doesn’t taste nearly as delicious! The secret to making the best lemon curd? Adding in cold butter at the end. It gives the curd the most delicious silky soft texture and thickens it beautifully.',
    instructions: 'Lemon curd is one of the easiest things to make, it’s a thick spread made from fresh lemons, sugar, eggs, and butter. It’s smooth, and creamy in texture with a bright, sweet, and zingy flavor perfect for using in desserts or simply spreading on toast for breakfast. Once you make this easy homemade version I guarantee you’ll never be tempted to pick up a jar at the store again because it doesn’t taste nearly as delicious! The secret to making the best lemon curd? Adding in cold butter at the end. It gives the curd the most delicious silky soft texture and thickens it beautifully.',
    filePath: '../../../../assets/recipe/French-Toast-Feature-360x495.jpg'
  },
  {
    id: 6,
    title: 'LEMON CURD',
    category: 'Smoothie',
    caption: 'How to make the easiest homemade Lemon Curd with just four simple ingredients. It\'s sweet, tart, smooth and creamy, and can be used in so many ways from filling cakes, tarts, scones and so much more!',
    preparationTime: '2',
    isFavourite: false,
    cookTime: '3',
    servings: 5,
    description: 'Lemon curd is one of the easiest things to make, it’s a thick spread made from fresh lemons, sugar, eggs, and butter. It’s smooth, and creamy in texture with a bright, sweet, and zingy flavor perfect for using in desserts or simply spreading on toast for breakfast. Once you make this easy homemade version I guarantee you’ll never be tempted to pick up a jar at the store again because it doesn’t taste nearly as delicious! The secret to making the best lemon curd? Adding in cold butter at the end. It gives the curd the most delicious silky soft texture and thickens it beautifully.',
    ingredients: 'Lemon curd is one of the easiest things to make, it’s a thick spread made from fresh lemons, sugar, eggs, and butter. It’s smooth, and creamy in texture with a bright, sweet, and zingy flavor perfect for using in desserts or simply spreading on toast for breakfast. Once you make this easy homemade version I guarantee you’ll never be tempted to pick up a jar at the store again because it doesn’t taste nearly as delicious! The secret to making the best lemon curd? Adding in cold butter at the end. It gives the curd the most delicious silky soft texture and thickens it beautifully.',
    instructions: 'Lemon curd is one of the easiest things to make, it’s a thick spread made from fresh lemons, sugar, eggs, and butter. It’s smooth, and creamy in texture with a bright, sweet, and zingy flavor perfect for using in desserts or simply spreading on toast for breakfast. Once you make this easy homemade version I guarantee you’ll never be tempted to pick up a jar at the store again because it doesn’t taste nearly as delicious! The secret to making the best lemon curd? Adding in cold butter at the end. It gives the curd the most delicious silky soft texture and thickens it beautifully.',
    filePath: '../../../../assets/recipe/Cream-puffs-feature-1-360x495.jpg'
  },
  {
    id: 7,
    title: 'LEMON CURD',
    category: 'Smoothie',
    caption: 'How to make the easiest homemade Lemon Curd with just four simple ingredients. It\'s sweet, tart, smooth and creamy, and can be used in so many ways from filling cakes, tarts, scones and so much more!',
    preparationTime: '2',
    isFavourite: false,
    cookTime: '3',
    servings: 5,
    description: 'Lemon curd is one of the easiest things to make, it’s a thick spread made from fresh lemons, sugar, eggs, and butter. It’s smooth, and creamy in texture with a bright, sweet, and zingy flavor perfect for using in desserts or simply spreading on toast for breakfast. Once you make this easy homemade version I guarantee you’ll never be tempted to pick up a jar at the store again because it doesn’t taste nearly as delicious! The secret to making the best lemon curd? Adding in cold butter at the end. It gives the curd the most delicious silky soft texture and thickens it beautifully.',
    ingredients: 'Lemon curd is one of the easiest things to make, it’s a thick spread made from fresh lemons, sugar, eggs, and butter. It’s smooth, and creamy in texture with a bright, sweet, and zingy flavor perfect for using in desserts or simply spreading on toast for breakfast. Once you make this easy homemade version I guarantee you’ll never be tempted to pick up a jar at the store again because it doesn’t taste nearly as delicious! The secret to making the best lemon curd? Adding in cold butter at the end. It gives the curd the most delicious silky soft texture and thickens it beautifully.',
    instructions: 'Lemon curd is one of the easiest things to make, it’s a thick spread made from fresh lemons, sugar, eggs, and butter. It’s smooth, and creamy in texture with a bright, sweet, and zingy flavor perfect for using in desserts or simply spreading on toast for breakfast. Once you make this easy homemade version I guarantee you’ll never be tempted to pick up a jar at the store again because it doesn’t taste nearly as delicious! The secret to making the best lemon curd? Adding in cold butter at the end. It gives the curd the most delicious silky soft texture and thickens it beautifully.',
    filePath: '../../../../assets/recipe/Cream-puffs-feature-1-360x495.jpg'
  },
  {
    id: 8,
    title: 'LEMON CURD',
    category: 'Smoothie',
    caption: 'How to make the easiest homemade Lemon Curd with just four simple ingredients. It\'s sweet, tart, smooth and creamy, and can be used in so many ways from filling cakes, tarts, scones and so much more!',
    preparationTime: '2',
    isFavourite: true,
    cookTime: '3',
    servings: 5,
    description: 'Lemon curd is one of the easiest things to make, it’s a thick spread made from fresh lemons, sugar, eggs, and butter. It’s smooth, and creamy in texture with a bright, sweet, and zingy flavor perfect for using in desserts or simply spreading on toast for breakfast. Once you make this easy homemade version I guarantee you’ll never be tempted to pick up a jar at the store again because it doesn’t taste nearly as delicious! The secret to making the best lemon curd? Adding in cold butter at the end. It gives the curd the most delicious silky soft texture and thickens it beautifully.',
    ingredients: 'Lemon curd is one of the easiest things to make, it’s a thick spread made from fresh lemons, sugar, eggs, and butter. It’s smooth, and creamy in texture with a bright, sweet, and zingy flavor perfect for using in desserts or simply spreading on toast for breakfast. Once you make this easy homemade version I guarantee you’ll never be tempted to pick up a jar at the store again because it doesn’t taste nearly as delicious! The secret to making the best lemon curd? Adding in cold butter at the end. It gives the curd the most delicious silky soft texture and thickens it beautifully.',
    instructions: 'Lemon curd is one of the easiest things to make, it’s a thick spread made from fresh lemons, sugar, eggs, and butter. It’s smooth, and creamy in texture with a bright, sweet, and zingy flavor perfect for using in desserts or simply spreading on toast for breakfast. Once you make this easy homemade version I guarantee you’ll never be tempted to pick up a jar at the store again because it doesn’t taste nearly as delicious! The secret to making the best lemon curd? Adding in cold butter at the end. It gives the curd the most delicious silky soft texture and thickens it beautifully.',
    filePath: '../../../../assets/recipe/French-Toast-Feature-360x495.jpg'
  },
  {
    id: 9,
    title: 'LEMON CURD',
    category: 'Smoothie',
    caption: 'How to make the easiest homemade Lemon Curd with just four simple ingredients. It\'s sweet, tart, smooth and creamy, and can be used in so many ways from filling cakes, tarts, scones and so much more!',
    preparationTime: '2',
    isFavourite: false,
    cookTime: '3',
    servings: 5,
    description: 'Lemon curd is one of the easiest things to make, it’s a thick spread made from fresh lemons, sugar, eggs, and butter. It’s smooth, and creamy in texture with a bright, sweet, and zingy flavor perfect for using in desserts or simply spreading on toast for breakfast. Once you make this easy homemade version I guarantee you’ll never be tempted to pick up a jar at the store again because it doesn’t taste nearly as delicious! The secret to making the best lemon curd? Adding in cold butter at the end. It gives the curd the most delicious silky soft texture and thickens it beautifully.',
    ingredients: 'Lemon curd is one of the easiest things to make, it’s a thick spread made from fresh lemons, sugar, eggs, and butter. It’s smooth, and creamy in texture with a bright, sweet, and zingy flavor perfect for using in desserts or simply spreading on toast for breakfast. Once you make this easy homemade version I guarantee you’ll never be tempted to pick up a jar at the store again because it doesn’t taste nearly as delicious! The secret to making the best lemon curd? Adding in cold butter at the end. It gives the curd the most delicious silky soft texture and thickens it beautifully.',
    instructions: 'Lemon curd is one of the easiest things to make, it’s a thick spread made from fresh lemons, sugar, eggs, and butter. It’s smooth, and creamy in texture with a bright, sweet, and zingy flavor perfect for using in desserts or simply spreading on toast for breakfast. Once you make this easy homemade version I guarantee you’ll never be tempted to pick up a jar at the store again because it doesn’t taste nearly as delicious! The secret to making the best lemon curd? Adding in cold butter at the end. It gives the curd the most delicious silky soft texture and thickens it beautifully.',
    filePath: '../../../../assets/recipe/Cream-puffs-feature-1-360x495.jpg'
  },
  {
    id: 10,
    title: 'LEMON CURD',
    category: 'Smoothie',
    caption: 'How to make the easiest homemade Lemon Curd with just four simple ingredients. It\'s sweet, tart, smooth and creamy, and can be used in so many ways from filling cakes, tarts, scones and so much more!',
    preparationTime: '2',
    isFavourite: false,
    cookTime: '3',
    servings: 5,
    description: 'Lemon curd is one of the easiest things to make, it’s a thick spread made from fresh lemons, sugar, eggs, and butter. It’s smooth, and creamy in texture with a bright, sweet, and zingy flavor perfect for using in desserts or simply spreading on toast for breakfast. Once you make this easy homemade version I guarantee you’ll never be tempted to pick up a jar at the store again because it doesn’t taste nearly as delicious! The secret to making the best lemon curd? Adding in cold butter at the end. It gives the curd the most delicious silky soft texture and thickens it beautifully.',
    ingredients: 'Lemon curd is one of the easiest things to make, it’s a thick spread made from fresh lemons, sugar, eggs, and butter. It’s smooth, and creamy in texture with a bright, sweet, and zingy flavor perfect for using in desserts or simply spreading on toast for breakfast. Once you make this easy homemade version I guarantee you’ll never be tempted to pick up a jar at the store again because it doesn’t taste nearly as delicious! The secret to making the best lemon curd? Adding in cold butter at the end. It gives the curd the most delicious silky soft texture and thickens it beautifully.',
    instructions: 'Lemon curd is one of the easiest things to make, it’s a thick spread made from fresh lemons, sugar, eggs, and butter. It’s smooth, and creamy in texture with a bright, sweet, and zingy flavor perfect for using in desserts or simply spreading on toast for breakfast. Once you make this easy homemade version I guarantee you’ll never be tempted to pick up a jar at the store again because it doesn’t taste nearly as delicious! The secret to making the best lemon curd? Adding in cold butter at the end. It gives the curd the most delicious silky soft texture and thickens it beautifully.',
    filePath: '../../../../assets/recipe/Cream-puffs-feature-1-360x495.jpg'
  },
  {
    id: 11,
    title: 'LEMON CURD',
    category: 'Smoothie',
    caption: 'How to make the easiest homemade Lemon Curd with just four simple ingredients. It\'s sweet, tart, smooth and creamy, and can be used in so many ways from filling cakes, tarts, scones and so much more!',
    preparationTime: '2',
    isFavourite: true,
    cookTime: '3',
    servings: 5,
    description: 'Lemon curd is one of the easiest things to make, it’s a thick spread made from fresh lemons, sugar, eggs, and butter. It’s smooth, and creamy in texture with a bright, sweet, and zingy flavor perfect for using in desserts or simply spreading on toast for breakfast. Once you make this easy homemade version I guarantee you’ll never be tempted to pick up a jar at the store again because it doesn’t taste nearly as delicious! The secret to making the best lemon curd? Adding in cold butter at the end. It gives the curd the most delicious silky soft texture and thickens it beautifully.',
    ingredients: 'Lemon curd is one of the easiest things to make, it’s a thick spread made from fresh lemons, sugar, eggs, and butter. It’s smooth, and creamy in texture with a bright, sweet, and zingy flavor perfect for using in desserts or simply spreading on toast for breakfast. Once you make this easy homemade version I guarantee you’ll never be tempted to pick up a jar at the store again because it doesn’t taste nearly as delicious! The secret to making the best lemon curd? Adding in cold butter at the end. It gives the curd the most delicious silky soft texture and thickens it beautifully.',
    instructions: 'Lemon curd is one of the easiest things to make, it’s a thick spread made from fresh lemons, sugar, eggs, and butter. It’s smooth, and creamy in texture with a bright, sweet, and zingy flavor perfect for using in desserts or simply spreading on toast for breakfast. Once you make this easy homemade version I guarantee you’ll never be tempted to pick up a jar at the store again because it doesn’t taste nearly as delicious! The secret to making the best lemon curd? Adding in cold butter at the end. It gives the curd the most delicious silky soft texture and thickens it beautifully.',
    filePath: '../../../../assets/recipe/Cream-puffs-feature-1-360x495.jpg'
  },
  {
    id: 12,
    title: 'LEMON CURD',
    category: 'Smoothie',
    caption: 'How to make the easiest homemade Lemon Curd with just four simple ingredients. It\'s sweet, tart, smooth and creamy, and can be used in so many ways from filling cakes, tarts, scones and so much more!',
    preparationTime: '2',
    isFavourite: true,
    cookTime: '3',
    servings: 5,
    description: 'Lemon curd is one of the easiest things to make, it’s a thick spread made from fresh lemons, sugar, eggs, and butter. It’s smooth, and creamy in texture with a bright, sweet, and zingy flavor perfect for using in desserts or simply spreading on toast for breakfast. Once you make this easy homemade version I guarantee you’ll never be tempted to pick up a jar at the store again because it doesn’t taste nearly as delicious! The secret to making the best lemon curd? Adding in cold butter at the end. It gives the curd the most delicious silky soft texture and thickens it beautifully.',
    ingredients: 'Lemon curd is one of the easiest things to make, it’s a thick spread made from fresh lemons, sugar, eggs, and butter. It’s smooth, and creamy in texture with a bright, sweet, and zingy flavor perfect for using in desserts or simply spreading on toast for breakfast. Once you make this easy homemade version I guarantee you’ll never be tempted to pick up a jar at the store again because it doesn’t taste nearly as delicious! The secret to making the best lemon curd? Adding in cold butter at the end. It gives the curd the most delicious silky soft texture and thickens it beautifully.',
    instructions: 'Lemon curd is one of the easiest things to make, it’s a thick spread made from fresh lemons, sugar, eggs, and butter. It’s smooth, and creamy in texture with a bright, sweet, and zingy flavor perfect for using in desserts or simply spreading on toast for breakfast. Once you make this easy homemade version I guarantee you’ll never be tempted to pick up a jar at the store again because it doesn’t taste nearly as delicious! The secret to making the best lemon curd? Adding in cold butter at the end. It gives the curd the most delicious silky soft texture and thickens it beautifully.',
    filePath: '../../../../assets/recipe/Cream-puffs-feature-1-360x495.jpg'
  }];
